spring.application.name=Carrer-backend

server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/Career-Forge
spring.datasource.username=postgres
spring.datasource.password=postgres

jwt.secret=8f4c9b7d3a2e6f0a9d1c5b8e7f4a6c2d9e0b1a3f5c8d6e2a4b7f9c1d0e6a8b
